### ISSUE TITLE
Help  with compiling

### ISSUE THREAD

**Issue by tomasDelizia** [Joy-Division/ArmsDepot#2]
Hi, I have issues when I try to compile most of the C files with gcc (also tried Dev-C++). I don't know what's going on. So far, I've only managed to compile dar-extract_pc, dar-extract_psp, dat-merge, gcx-decompile and qar-extract_psp. All the other files give me issues. Here are a few examples:
![Screenshot (322)](https://user-images.githubusercontent.com/68579667/97095025-da33c800-1630-11eb-91a9-a13c3927b1b3.png)
Hope you can help me.

**Comment by GirianSeed** [comment]
>So far, I've only managed to compile dar-extract_pc, dar-extract_psp, dat-merge, gcx-decompile and qar-extract_psp.

Those build because they have no dependencies. The Makefile should handle everything for you; all you have to do is call ``make`` on the command line. Also, be sure zlib is installed on your system since several tools depend on it.

**Comment by tomasDelizia** [comment]
I'm dumb, lmao. Thanks for the help!
