### ISSUE TITLE
Help with getting compiled

### ISSUE THREAD

**Issue by MHWModder** [Joy-Division/ArmsDepot#3]
I've tried using both GCC and Visual Studio and still cannot wrap my head around how I'm supposed to compile this. Is it possible to make a release for the project, or just share an already compiled version?

**Comment by GirianSeed** [comment]
See my reply to #2 and let me know if you still have trouble building the tools.
https://github.com/Joy-Division/tools-mgs/issues/2#issuecomment-716099519

They were originally written with a Linux environment in mind but they should build fine using MSYS2 or Cygwin on Windows.
