### ISSUE TITLE
I cannot build on Windows 10

### ISSUE THREAD

**Issue by repsonate** [Joy-Division/ArmsDepot#4]
Hello, so i've been trying to compile this for half a day yet nothing works. I tried GCC and Cygwyn, tried to build .c files as well as Makefile, but nothing works. I'm having the same errors that other user reported.
Is it possible to add a pre-compiled release, please?

**Comment by repsonate** [comment]
Ok, I solved the issue by using MSYS2 compiler. The Makefile worked successfully! Cheers!

**Comment by ShizCalev** [comment]
[tools-mgs_-_Arms_Depot.zip](https://github.com/Joy-Division/tools-mgs/files/14152182/tools-mgs_-_Arms_Depot.zip)
here's a precompiled version for anyone that has issues in the future. i got complication working with cygwyn.

**Comment by tastez** [comment]
^ this needs cygz cygwin1 dlls to run
