### ISSUE TITLE
i cant extract txt from stage.dat mgs2

### ISSUE THREAD

**Issue by nackedsnake** [Joy-Division/ArmsDepot#5]
He's extracting some files hdr and directories, but there's not any text
Its writing "Couldnt open dictionary /Metal Gear Solid - Tools/mgs2-w15a.txt
w" and writing this with other files

**Comment by ShizCalev** [comment]
https://github.com/Jayveer/Arsenal

Use this for MGS2.

**Comment by GirianSeed** [comment]
> Its writing "Couldnt open dictionary /Metal Gear Solid - Tools/mgs2-w15a.txt w" and writing this with other files

You can ignore those messages; they just indicate that no dictionary was loaded for that stage. All extracted files will be named for the hashes without a dictionary.

You can find my MGS2 stage.dat dictionaries here, although you'll need to prefix each .txt file with ``mgs2-`` to get the tool to load them. https://github.com/Joy-Division/JoyDict/tree/master/mgs2/stage.dat
